package net.sf.jclec.exprtree;

import net.sf.jclec.IPopulation;
import net.sf.jclec.ISpecies;
import net.sf.jclec.ISystem;
import net.sf.jclec.ITool;
import net.sf.jclec.exprtree.fun.AbstractPrimitive;
import net.sf.jclec.exprtree.fun.ExprTreeFunction;
import net.sf.jclec.ge.GESpecies;
import net.sf.jclec.util.random.IRandGen;
import net.sf.jclec.util.range.IRange;

/**
 * Represents a constant in a symbolic regression problem.
 * 
 * @author Rafael Barbudo Lunar
 */

public class Constant extends AbstractPrimitive implements ITool
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -4349262554064087860L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------- Internal variables
	/////////////////////////////////////////////////////////////////
	
	/** Constant value */
	
	private Double value = null;

	/** Random generator used in constant creation */
	
	protected IRandGen randgen;
	
	/** Constant schema */
	
	protected IRange schema;
	
	/** Context */
	
	protected ISystem context;
	
	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public Constant() 
	{
		super(new Class<?> [] {Double.class, Double.class}, Double.class);				
		//setValue(schema.getRandom(randgen));
	}

	/////////////////////////////////////////////////////////////////
	// -------------------------------------------- Protected methods
	/////////////////////////////////////////////////////////////////
	
	@Override
	protected void evaluate(ExprTreeFunction context) 
	{
		push(context,getValue());	
	}
	
	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////
	
	public void setValue(double value) 
	{
		this.value = value;
	}

	public double getValue() 
	{
		return value;
	}

	@Override
	public IPrimitive copy() 
	{
		Constant cNew = new Constant();
		cNew.value = new Double(this.value);
		cNew.context = this.context;
		cNew.randgen = this.randgen;
		cNew.schema = this.schema;
		
		return cNew;
	}

	@Override
	public IPrimitive instance() 
	{
		Constant cNew = new Constant();
		cNew.contextualize(context);
		return cNew;
	}
	
	public String toString()
	{
		return value.toString();
	}

	@Override
	public void contextualize(ISystem context) 
	{
		// TODO hay que ver si el esquema es un array o no, y si este es el 
		//      mejor lugar para establecer el valor de la constante
		
		ISpecies spc = ((IPopulation)context).getSpecies();
		if(spc instanceof GESpecies) {
			this.schema = ((GESpecies)spc).getGenotypeSchema().getIndividualConstants()[0];
		}
		this.randgen = context.createRandGen();
		setValue(schema.getRandom(randgen));
	}	
}