package net.sf.jclec.ge.mut;

import org.apache.commons.configuration.Configuration;
import org.apache.commons.configuration.ConfigurationRuntimeException;

import net.sf.jclec.IConfigure;
import net.sf.jclec.IPopulation;
import net.sf.jclec.ISystem;
import net.sf.jclec.ITool;
import net.sf.jclec.ge.GEIndividual;
import net.sf.jclec.util.opt.IOptimizer;

public class OptOneLocusMutator extends OneLocusMutator implements IConfigure
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////

	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -1756869206810217866L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------- Internal variables
	/////////////////////////////////////////////////////////////////

	/** Local optimizer */
	
	protected IOptimizer optimizer;
	
	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////
	
	/*
	 *  Equivalente al metodo mutateNext del original pero incluyendo además
	 *  optimizacion con Nelder Mead
	 */
	
	protected void mutateNext() 
	{
		// Genome length
		int gl = species.getGenotypeLength();
		// Individual to mutate
		GEIndividual mutant = 
			(GEIndividual) parentsBuffer.get(parentsCounter);
		// Creates mutant genotype
		int [] mgenome = new int[gl];
		System.arraycopy(mutant.getGenotype(), 0, mgenome, 0, gl);
		// Choose mutation point
		int mp = getMutableLocus();
		// Flip selected point
		flip(mgenome, mp);
		mutant.setGenotype(mgenome);
		//System.out.println("constantes mutante:"+mutant.getConstants()[0] + " " + mutant.getConstants()[1] + " " +mutant.getConstants()[2] + " " +mutant.getConstants()[3]);
		GEIndividual optimizado = (GEIndividual) optimizer.optimize(mutant);
		//System.out.println("constantes optimizado:"+optimizado.getConstants()[0] + " " + optimizado.getConstants()[1] + " " +optimizado.getConstants()[2] + " " +optimizado.getConstants()[3]);
		// Returns mutant
		sonsBuffer.add(optimizado);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public void configure(Configuration configuration) {

		try {
			// Get the local optimizer
			String optimizerName = configuration.getString("optimizer[@type]");			
			// Optimizer class
			Class<? extends IOptimizer> optimizerClass = 
				(Class<? extends IOptimizer>) Class.forName(optimizerName);
			// Optimizer instance
			IOptimizer optimizer = optimizerClass.newInstance();
			// Configure species
			if (optimizer instanceof IConfigure) {
				((IConfigure) optimizer).configure(configuration.subset("optimizer"));
			}
			// Set the optimizer
			this.optimizer = optimizer;
		} 
		catch (ClassNotFoundException e) {
			throw new ConfigurationRuntimeException("Illegal optimizer classname");
		} 
		catch (InstantiationException e) {
			throw new ConfigurationRuntimeException("Problems creating an instance of optimizer", e);
		} 
		catch (IllegalAccessException e) {
			throw new ConfigurationRuntimeException("Problems creating an instance of optimizer", e);
		}	
	}
	
	public final void contextualize(ISystem context)
	{
		if(context instanceof IPopulation) {
			// Contextualize this operator
			this.context = (IPopulation) context;
			// Attach a random generator to this object
			this.randgen = context.createRandGen();
			if(this.optimizer instanceof ITool)
				this.optimizer.contextualize(context);
		}
		else {
			throw new IllegalArgumentException("This object uses a population as execution context");
		}
	}
	
}
