package net.sf.jclec.ge.cre;

import net.sf.jclec.ge.GECreator;
import net.sf.jclec.ge.GEIndividual;

/**
 * GEIndividual creator which maps the phenotype with the full method.
 * 
 * @author Rafael Barbudo Lunar
 */

public class GEFullCreator extends GECreator 
{
	
	// TODO Comentar problema con individuos invalidos
	
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -7713253532808122758L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public GEFullCreator()
	{
		super();
	}
	
	/////////////////////////////////////////////////////////////////
	// -------------------------------------------- Protected methods
	/////////////////////////////////////////////////////////////////
	
	@Override
	protected void createNext() 
	{
		String rootSymbol = schema.getRootSymbol();
		int [] newGenotype = createGenotype();
		GEIndividual newInd = new GEIndividual(newGenotype);
		
		schema.full(newInd, rootSymbol, 0, 0);
		// Add the new individual
		createdBuffer.add(newInd);	
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////
	
	@Override
	public GEIndividual createIndividual(int[] genotype) 
	{
		GEIndividual newInd = new GEIndividual(genotype);		
		String rootSymbol = schema.getRootSymbol();
		
		schema.full(newInd, rootSymbol, 0, 0);
		
		return newInd;
	}
	
}
