package net.sf.jclec.ge.cre;

import java.util.ArrayList;
import java.util.List;

import net.sf.jclec.IIndividual;
import net.sf.jclec.ge.GECreator;
import net.sf.jclec.ge.GEIndividual;

/**
 * GEIndividual creator which maps the phenotype with the ramped half-and-half method.
 * 
 * @author Rafael Barbudo Lunar
 */

public class RampedHalfAndHalf extends GECreator 
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -2889517912372790322L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public RampedHalfAndHalf()
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// -------------------------------------------- Protected methods
	/////////////////////////////////////////////////////////////////
	
	@Override
	protected void createNext() 
	{
		String rootSymbol = schema.getRootSymbol();
		GEIndividual newInd = new GEIndividual(createGenotype());
		
		if(randgen.coin())
			schema.grow(newInd, rootSymbol, 0, 0);
		else
			schema.full(newInd, rootSymbol, 0, 0);

		// Add the new individual
		createdBuffer.add(newInd);
	}
	
	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////
	
	/**
	 * This method creates the initial population with the ramped half-and-half method
	 * 
	 * @param numberOfIndividuals The number of individual we want to create
	 * 
	 * @return a list which contains the individuals created 
	 * 
	 */
	
	public List<IIndividual> provide(int numberOfIndividuals) 
	{
		// Prepare process
		prepareCreation();
		// Set numberOfIndividuals
		this.numberOfIndividuals = numberOfIndividuals;
		// Result list
		createdBuffer = new ArrayList<IIndividual> (numberOfIndividuals);
		// Get the root symbol
		String rootSymbol = schema.getRootSymbol();
		// Original max depth
		int maxDepth = schema.getMaxDepthSize();
		// Current depth
		int currentDepth = schema.getMinDepthSize(rootSymbol);
		// Get the number of individuals for each group and the rest too
		int nOfIndividualPerGroup = numberOfIndividuals/(schema.getMaxDepthSize()-schema.getMinDepthSize(rootSymbol)+1);		
		
		for(int i=0; i<this.numberOfIndividuals; i++)
		{
			schema.setMaxDepthSize(currentDepth);
			GEIndividual newInd = new GEIndividual(createGenotype());
			// Map phenotype with grow or full method
			if(randgen.coin())
				schema.grow(newInd, rootSymbol, 0, 0);
			else
				schema.full(newInd, rootSymbol, 0, 0);	
			//Add the new individual
			createdBuffer.add(newInd);
			// Increase the current depth if it's necesary
			if(i%nOfIndividualPerGroup==0) {
				currentDepth++;
				if(currentDepth == maxDepth)
					currentDepth = schema.getMinDepthSize(rootSymbol);
			}
		}
		//Restore the original depth
		schema.setMaxDepthSize(maxDepth);
		return createdBuffer;
	}
	
	@Override
	public GEIndividual createIndividual(int[] genotype) 
	{		
		GEIndividual newInd = new GEIndividual(genotype);
		String rootSymbol = schema.getRootSymbol();		
						
		if(randgen.coin())
			schema.grow(newInd, rootSymbol, 0, 0);
		else
			schema.full(newInd, rootSymbol, 0, 0);

		return newInd;	
	}

}
